for i in range(1,25):
  if i == 1:
   print('* ' * i)
  elif i == 2:
    print('* ' * i)
  elif i == 3:
    print('* ' * i)
  elif i == 4:
    print('* ' * i)
  elif i == 5:
    print('* ' * i)
  elif i == 6:
    print('* ' * i)
  elif i == 7:
    print('* ' * i)
  elif i == 8:
    print('* ' * i)
  elif i == 9:
    print('* ' * i)
  elif i == 10:
    print('* ' * i)
  elif i == 11:
    print('* ' * i)
  elif i == 12:
    print('* ' * i)
  elif i == 13:
    print('* ' * i)
  elif i == 14:
    print('* ' * i)
  elif i == 15:
    print('* ' * i)
  elif i == 16:
    print('* ' * i)
  elif i == 17:
    print('* ' * i)
  elif i == 18:
    print('* ' * i)
  elif i == 19:
    print('* ' * i)
  elif i == 20:
    print('* ' * i)
  elif i == 21:
    print('* ' * i)
  elif i == 22:
    print('* ' * i)
  elif i == 23:
    print('* ' * i)
  elif i == 24:
    print('* ' * i)
  else:
    print('* ' * i)
